### ISSUE TITLE
نیاز به مستند سازی

### ISSUE THREAD

**Issue by mhbashari** [ehsan2022002/NER_FARSI#1]
سلام وقتتون به خیر
خیلی کار خوبی کردید که توی جاوا ابزارها رو لیست کردید. به هرحال جاوا هنوز انتخاب اول خیلی ها است.
به نظرم لیست نسبتا کاملی میاد ولی جای یه مستند سازی خوب خالی هست.

**Comment by ehsan2022002** [comment]
برای اطلاعات کامل و درک دقیق میتونید به کتاب زیر مراجعه کنید 
Taming Text -Manning Publications
 متن ساده و روانی داره در اینترنت هم گیر میاد. در مورد ابزارها البته روشهای کاملتری هم هست تنها به این مثالها اکتفا شده

**Comment by mhbashari** [comment]
منظورم زمینه ی دانشی نبود. منظورم این بود که راهی برای توسعه اش توسط دیگران باز بشه.
منظورم مستندات توسعه ای بود نه مستندات دانشی
به هر حال خسته نباشید.
